{% set name = "Pebble" %}
{% set version = "5.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | lower }}-{{ version }}.tar.gz
  sha256: 8e0a5f6a1cfdd0ac1bfc4a789e20d2b4b895de976e547d23b7de23b71ef39b34

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - pebble
    - pebble.concurrent
    - pebble.pool

about:
  home: https://pebble.readthedocs.io/
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: Pebble provides a neat API to manage threads and processes within an application.
  dev_url: https://github.com/noxdafox/pebble

extra:
  recipe-maintainers:
    - hoechenberger
