{% set name = "Pebble" %}
{% set version = "5.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2784c147766f06388cea784084b14bec93fdbaa793830f1983155aa330a2a6e4

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - pebble
    - pebble.concurrent
    - pebble.pool

about:
  home: https://pebble.readthedocs.io/
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: Pebble provides a neat API to manage threads and processes within an application.
  dev_url: https://github.com/noxdafox/pebble

extra:
  recipe-maintainers:
    - hoechenberger
