{% set name = "Pebble" %}
{% set version = "5.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | lower }}-{{ version }}.tar.gz
  sha256: eb49a0f6862f7e75df4a40107f1c8c267cf8adfbd6d29a0dac29d17ac188c878

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - pebble
    - pebble.concurrent
    - pebble.pool

about:
  home: https://pebble.readthedocs.io/
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: Pebble provides a neat API to manage threads and processes within an application.
  dev_url: https://github.com/noxdafox/pebble

extra:
  recipe-maintainers:
    - hoechenberger
